# filename: nodejs-with-webpack.yml
name: NodeJS with Webpack

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    env:
      NPM_AUTH_TOKEN: Ynk5UlluQjNUa3hDVVhSRmIwUldVMUpOU0VsV2RuQnVhR2xxTjFGdE5UVjROV3hSSzFKVmN6Qm9RVTFJVEdaa1FUVkJUbk5HV1dWWE9GUjVaRVozVG5adFNXUXZXbnBIZUV0dU1qWlRhbTVNVDFveVYyc3pialJ1ZFVSNU1VSXJSWFpVZVU1UGVXMXVTR2sxU0VKNGRWTjNRMlZPTjIxNGFXOUdVMnB5ZVZWR01tUTRkM2hJWW0xc1JqVlRjSFpVV0hVME5uWXlaRTVHU25OWWJuVjNOMnRXV2tnelVsSkpNVVpYZUZoRFVrb3pkbE0yUW5oc05sUlphbEJIV1M5dWFUZHZZbVZxY0ZZNE5tbGxObVJ2TUZrek9ERm9kMVl2Y2l0RFpsZHpWR0ZNYkhKeVpWSkVabmhXUkV0amMydHpTVGxsUjNCdU9IZG5aM2swUkRKeFdEbFBhSEk1WWpscVdVbEpRMWdyU0dKQ05sTnlRV3RsUzFKVWFHbEJRVmxEUjBaRk4zVllMMjVYTXpoaWVYZzBTVzgxYkVSNU1sUnBRVGhzY1ZKaWRFeFJiRTFuVkZsaE56QjVXV3B1Wld0cGJucDFiM05LT1ZKYVpUQlFRVkZpWm1SbE9WcE5NRzV6ZWtOcGJuVnhUMUZFYzIxWGFYTklZeTh5VDJKRlpUYzNVR3BKVVU5YVdraE1SelpKTjJ4b2EzUm1SVEF3ZUdNMFduaG5WMGx5Wmxac1JtbGFiRTEwVkZSWlNrbDZTMVl2WTJVM2RFWlRSRlpDTms5clZIUk9ja2h3WkhCbmRWQjJTMVpJZFdaWVRYQnFlSEkzUTBsM2FIYzVlRGRPYVdsWlJXTkpTMGt2ZEVWT00xTllNa1JHZWt3dlNFaHNaRkJyY21SMk1IaE9SM1JDWkhwdGJqSk9aVVUwTkVKV2RGUnVhRE5oYzBKR1QwODVUMk1yVmpNMFJVVlpOVFZyZFVoU2FVOUpXQzhyY2tOd01Xc3pXVGx1WTNkbU5GVTNlRTlRY2l0SFNHWkhWRlZOYTJRNVowaGtkRnB5WVc5Q00zQTRZaTg1Y2lzMVJsWnpSSEZJTXpORlFXdEVOazF6T1dkeGEzaFpXV1JMWVhkWlRIQkhkbVZPTUdkaVUxUnNSa3RhVVROVllYcEhNa0pIVUhFMk1XbFhkbGwwTDJobFowWkhaMlZzZG5NeVJrRm1VV1o0YzJkUk0xQkljbXA2VFRoS1NGaEVMemhQUmpGVmJXNHdNbEoxZUdoWmFVeFZaRWhDUVVOVlVTdFljU3RWZUhaRFREUm1RMjFPV1dsUFdYbDNWelZDY1VWSGFrRnBVR3gwY21reVUzUXpTRTl3UW5OMldHVnpjMUI2U2s1MmVXRTJNMUptUjJZM05rSXhOMmxDTVRWbVQxazFTekpCVUVKeFRrY3hZMFI2ZDI5ME9IbHNOQ3RsVVhWYUwwTnliWGt4ZDA5S1ozWTRXR2xpUTI5b1NtOXhNbVI1T0dKTk1rMU5la2wwWXpacFpIaHhkbGRaYkhoekt6SjRjMnQxVjJzelIwMXpUbTlNZVhSbEwxTktiMUp5Y2tWdWVGTkxjWGxtYmxkQk4waG1OM0JtVWpWM1ptbFBkVGg0Y0RSWk5tWTFlVVZ0ZVcxRlIxUlJOa1l3UzBoTlYwbzBhMFpEY0ZCVWMydzFRM2tyYUhscGFVbFFha05UU1ZWTlFrUTRMMlkyVUhGRE9UTk9Rbkp6WlVob1JYZFdkM2xzTjFSb1JUaDFhMjlIYzJWWWRXbFdhRGQxZVhwbU9XbzBPRzFrZFU1TlJFbGtkRFZZUjJOSEsybDFWU3RKUm5OcU1WSlRjeXNyYWtFOVBRPT0=

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present
